
version: "3"

services:

  broker:

    image: registry.access.redhat.com/jboss-amq-6/amq63-openshift:1.4

    ports:
      - 5672:5672

  sender:

    build: sender/

    command: python ./sender.py

    depends_on:
      - broker

  receiver:

    build: receiver/
 
    command: python ./receiver.py

    depends_on:
      - broker
